### ISSUE TITLE
coordinate bug in correction debugger

### ISSUE THREAD

**Issue by ruudvdent** [WAM2layers/WAM2layers#317] opened 2024-01-24 21:16 UTC
I was running a forward tracking test experiment. I got an error the moment the stability correction is invoked. Something with writing the correction file to netcdf doesn't properly with the coordinates. In fact the longitude has length 281 and latitude 161.

````
wam2layers forwardtrack  Moisture_tracking_cases/West_Africa_1998_JA.yaml 
Welcome to WAM2layers.
Starting forwardtrack experiment.
Initializing experiment with config file Moisture_tracking_cases/West_Africa_1998_JA.yaml
Output will be written to /home/rjvanderent/Moisture_tracking_cases/West_Africa_JA/output_data.
1998-07-02 00:00:00 - Tracked moisture: 1.85%. Tagged in atmosphere: 98.15%. Lost moisture: 0.00%. Gained moisture: 0.00%. Tagging closure: 100.00%. Time since start: 33.09s, RAM: 49.61 MB
1998-07-02 00:00:00 - Writing output to file /home/rjvanderent/Moisture_tracking_cases/West_Africa_JA/output_data/forwardtrack_1998-07-02T00-00.nc
1998-07-03 00:00:00 - Tracked moisture: 9.99%. Tagged in atmosphere: 90.01%. Lost moisture: 0.00%. Gained moisture: 0.00%. Tagging closure: 100.00%. Time since start: 71.11s, RAM: 63.06 MB
1998-07-03 00:00:00 - Writing output to file /home/rjvanderent/Moisture_tracking_cases/West_Africa_JA/output_data/forwardtrack_1998-07-03T00-00.nc
Traceback (most recent call last):
  File "/home/rjvanderent/miniconda3/envs/wam_env/bin/wam2layers", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/rjvanderent/miniconda3/envs/wam_env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjvanderent/miniconda3/envs/wam_env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/rjvanderent/miniconda3/envs/wam_env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjvanderent/miniconda3/envs/wam_env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjvanderent/miniconda3/envs/wam_env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjvanderent/WAM2layers/src/wam2layers/cli.py", line 103, in forwardtrack
    run_forwardtrack_experiment(config_file)
  File "/home/rjvanderent/WAM2layers/src/wam2layers/tracking/forwardtrack.py", line 217, in run_experiment
    stabilize_fluxes(F, S0, progress_tracker, config, t0)
  File "/home/rjvanderent/WAM2layers/src/wam2layers/preprocessing/shared.py", line 362, in stabilize_fluxes
    progress_tracker.track_stability_correction(fy_limit, fy_abs, config, coords, t)
  File "/home/rjvanderent/WAM2layers/src/wam2layers/utils/profiling.py", line 132, in track_stability_correction
    ncfile = xr.DataArray(correction, coords=coords, name="correction")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjvanderent/miniconda3/envs/wam_env/lib/python3.11/site-packages/xarray/core/dataarray.py", line 423, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjvanderent/miniconda3/envs/wam_env/lib/python3.11/site-packages/xarray/core/dataarray.py", line 169, in _infer_coords_and_dims
    raise ValueError(
ValueError: conflicting sizes for dimension 'longitude': length 161 on the data but length 281 on coordinate 'longitude'
'''

**Comment by ruudvdent** [comment] 2024-01-24 21:17
I am going to try what happens if I simply skip writing out the correction file, but that's not an ideal solution of course

**Comment by Peter9192** [comment] 2024-01-25 10:10
Could you insert a debug statement before 

> src/wam2layers/utils/profiling.py", line 132

```py
import IPython; IPython.embed(); quit()
```

and then check the values of `correction` and `coords`?

**Comment by Peter9192** [comment] 2024-02-15 09:06
@BSchilperoort I think this is similar to the issue you encountered, right?

**Comment by BSchilperoort** [comment] 2024-02-15 09:16
Yup, this is the issue I encountered. So #324 is a duplicate of this issue.

To debug I used:

```py
from wam2layers.tracking.forwardtrack import (
    run_experiment as run_forwardtrack_experiment,
)

if __name__ == "__main__":
    config_file = "path_to_cfg"
    run_forwardtrack_experiment(config_file)
```
which I ran in VS Code using the debugger.

**Closed** 2024-02-16 12:32 UTC
